name: Deploy Vue to WordPress

on:
  push:
    branches:
      - main # Укажите ветку, на которую нужно настраивать деплой, например, main или master.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Используем последнюю версию checkout action

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Укажите нужную версию Node.js

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy to WordPress
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -c "
          set ssl:verify-certificate no;
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER;
          mirror -R --delete ./dist /www/softpear.ru/wp-content/themes/fu/vue/;
          quit"